calci/.vscode/settings.json, calci/README.md, calci/brian.js, calci/index.html, calci/style.css
This is a fully working calculator... Thanks for reading the pr
=> Calculator

tic-tac-toe_with_python/game.py, tic-tac-toe_with_python/readme.md
=> tic-toc-toe_game_python  from centiago001 for your repository on the occasion of hactoberfest2022

URL_Shrinker/Procfile, URL_Shrinker/app.js, URL_Shrinker/package-lock.json, URL_Shrinker/package.json, URL_Shrinker/views/index.ejs
=> URL shortener

Slide_Puzzle-Game/Readme.md, Slide_Puzzle-Game/mylinkedlist.h, Slide_Puzzle-Game/myqueue.h, Slide_Puzzle-Game/solution.cpp
=> Slide Puzzle Game in CPP

MovieSearch/index.css, MovieSearch/index.html, MovieSearch/index.js
=> added movie recommender application

RomanToDecimalConverter/index.html, RomanToDecimalConverter/scripts.js, RomanToDecimalConverter/styles.css
I created Roman numerals to convert in Decimal.
Hope you like and accept this PR.
=> Roman to Decimal converter

strong password generator/password.py
Run the code to generate a strong password
Signed-off-by: Author Name bhattacharyaaditya61@gmail.com
=> Added a code to generate strong password

Clock/Clock.py
Signed-off-by: Author Name ankushroy2001@gmail.com
=> Added a Clock Python script with Alarm and Stopwatch

CRUD Operations JavaScript/index.html, CRUD Operations JavaScript/script.js, CRUD Operations JavaScript/style.css
Please accept pull request and make valid for Hacktoberfest-2022.Thank you
=> Javascript CRUD operation

random_username_generator/README.md, random_username_generator/random_username_generator.py
adding random username generator that created using Python. I hope it can be useful :)
=> add random-username-generator program using python

Technical KBC/tek_kbc.c, password-generator-with-JavaScript/README.md, password-generator-with-JavaScript/app.js, password-generator-with-JavaScript/index.html, password-generator-with-JavaScript/style.css
Hi, I want to add a password generator project. This is a basic project created using JavaScript. It has already adjusted with OWASP in creating passwords. Well, I hope it is useful. Thanks.
=> Add password generator with javascript project

planetSimulation/main.py
please accept this pull request
=> added a planet simulator python code

calci/Calci_gui.py
Hi @Ghost-Ashu , please accept my PR for hacktoberfest 2022 :)
Signed-off-by: lok84 <lokseth20@gmail.com>
=> Contributing Python Code - GUI

editor/README.md, editor/editor.java
This code is used generate a editor which can be used to write docs
=> Editior using java

multithread/Multithread.java, multithread/README.md
Added a multithread for parallel processing...
=> Added a Multithread

Quote Generator/index.html, Quote Generator/script.js, Quote Generator/style.css
@Ghost-Ashu could you please have a look on my contribution. 
Thanks!!
=> added quote generator 

QRCodeGenerator/README.md, QRCodeGenerator/qrcode.py
Added a QR Code generator in python.
=> Added a qr generator in python

Custom Input Date/README.md, Custom Input Date/date.html, Custom Input Date/style.css
Custom input date using basics of html and css
=> Custom Input Date

online-marketing/store-website.html
i made this website using basic html. Please consider my pull request.
=> Created store-website.html

Note-Keeper/README.md, Note-Keeper/index.html, Note-Keeper/script.js, Note-Keeper/style.css
I have made this project using HTML, CSS and JavaScript. Kindly consider the pull request.
=> Added Note Keeper

musicstore/README.md, musicstore/index.html, musicstore/style.css
I have made a music store website using HTML and CSS in which users can sell and buy musical instruments.
=> Music Store Website

World_book.html
Added the code of world book project in html
=> Created world_book.html
